name = "passkey-demo"
main = "src/index.ts"
compatibility_date = "2023-01-01"
kv_namespaces = [
  { binding = "DB", id = "df9a6bb835e14ed4bfd4eb4a30bde037", preview_id = "078529e854b845b6956020f667f778bf" }
]
node_compat = false

[site]
bucket = "./static"